Food_Web/Models/Order_detail.cs
namespace Food_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Order_detail
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Od_id { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Productid { get; set; }

        public double? price { get; set; }

        public long? num { get; set; }

        public double? tt_money { get; set; }

        [StringLength(128)]
        public string Storeid { get; set; }

        public virtual Order Order { get; set; }

        public virtual Product Product { get; set; }

        [StringLength(50)]
        public string VoucherCode { get; set; }

        public double? Totalinvoucher { get; set; }
    }
}

Food_Web/Areas/Store/Controllers/Order_detailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Security;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using Aspose.Words;
using System.Diagnostics;
using DocumentFormat.OpenXml.Drawing.Charts;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using Microsoft.Security.Application;
using Microsoft.Extensions.Logging;
using PagedList;
using PagedList.Mvc;

namespace Food_Web.Areas.Store.Controllers
{
    public class Order_detailsController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();

        //GET: Store/Order_details
        public ActionResult Index(int? page)
        {
            // Get the currently logged-in user
            string userId = User.Identity.GetUserId();

            // Retrieve order details for the logged-in user
            var orderDetail = db.Order_detail
                .Include(o => o.Order)
                .Include(o => o.Product)
                .Where(o => o.Storeid == userId)
                .OrderBy(o => o.Od_id); // Replace YourProperty with the property you want to sort by

            const int pageSize = 10; // Set your desired page size
            int pageNumber = page ?? 1;

            // Apply pagination using ToPagedList method (not asynchronous)
            var pagedOrderDetails = orderDetail.ToPagedList(pageNumber, pageSize);

            return View(pagedOrderDetails);
        }


        // GET: Store/Order_details/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order_detail order_detail = await db.Order_detail.FindAsync(id);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            return View(order_detail);
        }


        [HttpPost]
        public ActionResult UpStatus(int id, bool status)
        {
            try
            {
                var orderDetail = db.Order_detail.FirstOrDefault(o => o.Order.Od_id == id);
                if (orderDetail == null)
                {
                    return Json(new { success = false, message = "Order not found." });
                }

                orderDetail.Order.Od_status = !status;
                db.SaveChanges();

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
        public ActionResult Orderday(DateTime? od_day, int? page)
        {
            var userId = User.Identity.GetUserId();
            var order_details = db.Order_detail.Include(o => o.Order).Include(o => o.Product);

            if (od_day.HasValue)
            {
                order_details = order_details
                    .Where(o => DbFunctions.TruncateTime(o.Order.Od_date) == DbFunctions.TruncateTime(od_day.Value) && o.Storeid == userId)
                    .OrderBy(o => o.Order.Od_date);
                Session["selcetodday"] = od_day;
            }
            else
            {
                order_details = order_details
                    .Where(o => o.Storeid == userId)
                    .OrderBy(o => o.Order.Od_date);
            }

            const int pageSize = 10;
            int pageNumber = page ?? 1;

            var pagedOrderDetails = order_details
                .ToPagedList(pageNumber, pageSize); // Use ToPagedList for pagination

            return View(pagedOrderDetails);
        }


        public ActionResult Exportod_day()
        {
            var userId = User.Identity.GetUserId();
            var selectedOdDay = Session["selcetodday"] as DateTime?; // Get the selected od_day from Session

            List<Order_detail> orderDetails;

            if (selectedOdDay.HasValue)
            {
                orderDetails = db.Order_detail
                    .Where(o => o.Storeid == userId && DbFunctions.TruncateTime(o.Order.Od_date) == DbFunctions.TruncateTime(selectedOdDay))
                    .ToList();
            }
            else
            {
                orderDetails = db.Order_detail
                    .Where(o => o.Storeid == userId)
                    .ToList();
            }

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Order Details");

                // Set the header row
                worksheet.Cells[1, 1].Value = "Order ID";
                worksheet.Cells[1, 2].Value = "Product ID";
                worksheet.Cells[1, 3].Value = "Total Money";
                worksheet.Cells[1, 4].Value = "Quantity";
                worksheet.Cells[1, 5].Value = "Price";
                worksheet.Cells[1, 6].Value = "Store ID";
                worksheet.Cells[1, 6].Value = "User ID";

                // Populate data rows
                for (int i = 0; i < orderDetails.Count; i++)
                {
                    var orderDetail = orderDetails[i];
                    worksheet.Cells[i + 2, 1].Value = orderDetail.Od_id;
                    worksheet.Cells[i + 2, 2].Value = orderDetail.Productid;
                    worksheet.Cells[i + 2, 3].Value = orderDetail.tt_money;
                    worksheet.Cells[i + 2, 4].Value = orderDetail.num;
                    worksheet.Cells[i + 2, 5].Value = orderDetail.price;
                    worksheet.Cells[i + 2, 6].Value = orderDetail.Storeid;
                    worksheet.Cells[i + 2, 7].Value = orderDetail.Order.Od_name;
                }

                // Auto-fit columns
                worksheet.Cells.AutoFitColumns();

                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment; filename=OrderDetails.xlsx");
                Response.BinaryWrite(package.GetAsByteArray());
                Response.End();
            }

            return View("success");
        }
        [HttpPost]
        public ActionResult GetOrderDetails(int orderId)
        {
            try
            {
                var orderDetails = db.Order_detail
                    .Where(od => od.Od_id == orderId)
                    .ToList();

                // Prepare the data to be sent back to the client
                var result = new
                {
                    success = true,
                    orderDetails = orderDetails.Select(od => new
                    {
                        productName = od.Product.Productname,
                        Gia = od.price,
                        soluong = od.num,
                        quantity = od.Totalinvoucher,
                        total = od.tt_money,
                        Status = od.Order.Od_status,
                        img = od.Product.image
                    })
                };

                return Json(result);
            }
            catch (Exception ex)
            {
                // Handle any errors and return an error response to the client
                var result = new
                {
                    success = false,
                    message = "An error occurred while retrieving order details."
                };

                // You may also log the error for further investigation
                // Log.Error(ex, "An error occurred while retrieving order details.");

                return Json(result);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Exportexcel()
        {
            // Get the currently logged-in user's ID
            string userId = User.Identity.GetUserId();

            var orderDetails = db.Order_detail
                .Include(od => od.Order)
                .Include(od => od.Product)
                .Where(od => od.Storeid == userId)
                .ToList();

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("OrderDetails");

                // Set the header row
                worksheet.Cells[1, 1].Value = "Order ID";
                worksheet.Cells[1, 2].Value = "Product Name";
                worksheet.Cells[1, 3].Value = "Price";
                worksheet.Cells[1, 4].Value = "Quantity";
                worksheet.Cells[1, 5].Value = "Total Money";
                //worksheet.Cells[1, 6].Value = "Status";
                worksheet.Cells[1, 7].Value = "Image";

                // Style the header row
                using (var range = worksheet.Cells[1, 1, 1, 7])
                {
                    range.Style.Font.Bold = true;
                    range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                    range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
                }

                // Populate data rows
                for (int i = 0; i < orderDetails.Count; i++)
                {
                    var orderDetail = orderDetails[i];
                    worksheet.Cells[i + 2, 1].Value = orderDetail.Order.Od_id;
                    worksheet.Cells[i + 2, 2].Value = orderDetail.Product.Productname;
                    worksheet.Cells[i + 2, 3].Value = orderDetail.price;
                    worksheet.Cells[i + 2, 4].Value = orderDetail.num;
                    worksheet.Cells[i + 2, 5].Value = orderDetail.tt_money;

Food_Web/Areas/Store/Views/Order_details/GetOrderDetails.cshtml
@{
    ViewBag.Title = "GetOrderDetails";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

@model IEnumerable<Food_Web.Models.Order_detail>

@foreach (var orderDetail in Model)
{
    <div>
        <p>Product Name: @orderDetail.Product.Productname</p>
        <p>Price: @orderDetail.price</p>
        <hr />
    </div>
}

Food_Web/Areas/Store/Views/Order_details/Index.cshtml
@model PagedList.IPagedList<Food_Web.Models.Order_detail>
@using PagedList;
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Food_Web.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
    //IdentityDbContext context = new IdentityDbContext();
    //var listUser = context.Users.ToList();
    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var listUser = userManager.Users.ToList();
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Trang Chủ", "Index", "Homes") / @Html.ActionLink("Voucher Giảm giá", "Index", "Discounts")</h6>
    </div>
    <a href="@Url.Action("Exportexcel", "Order_details")" class="btn btn-primary">Export to Excel</a>
    <table class="table">
        <tr>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        STT
                    </span>
                </div>
            </td>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Tên
                    </span>
                </div>
            </td>

            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Ngày Đặt
                    </span>
                </div>
            </td>

            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Hành Động
                    </span>
                </div>
            </td>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Od_id)
                </td>
                <td class="border">
                    @foreach (var u in listUser)
                    {
                        if (u.Id == item.Order.Od_name)
                        {
                            <span id="username">@u.Fullname</span>
                            <span id="Sdt" style="display: none;">@u.PhoneNumber</span>
                            <span id="adress" style="display: none;">@u.Adress</span>
                            break;
                        }
                        else { continue; }
                    }
                </td>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Order.Od_date)
                </td>
               
                <td class="border">
                    <button class="btn btn-primary btn-sm btn-view-details" data-id="@item.Od_id" data-bs-toggle="modal" data-bs-target="#detailsModal">
                        <i class="fas fa-eye"></i>
                    </button>
                </td>

            </tr>
        }


    </table>
</div>

<div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
    <div class="modal-dialog">

        <div class="modal-content" id="exportword">
            <div class="modal-header">
                <h5 class="modal-title" id="detailsModalLabel">Chi Tiết Hóa Đơn</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="orderDetailsContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <div>
                    @using (Html.BeginForm("ExportToPdf", "Order_details", new { area = "Store" }, FormMethod.Post, new { @id = "Export_form" }))
                    {
                        <input type="hidden" name="Gridhtml" />
                        <input type="submit" id="btnsubmit" value="Export" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-3">
    <nav aria-label="Page navigation">
        <ul class="pagination">

            @if (Model.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true">&laquo;</span>
                </li>
            }

            @for (var i = 1; i <= Model.PageCount; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                </li>
            }

            @if (Model.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true">&raquo;</span>
                </li>
            }

        </ul>
    </nav>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/docxtemplater/3.12.1/docxtemplater.js"></script>

<script>

    $(document).ready(function () {
        $(".btn-approve").on("click", function () {
            var button = $(this);
            var id = button.data("id");
            var status = button.hasClass("btn-success");

            $.ajax({
                url: '@Url.Action("UpStatus", "Order_details")',
                type: 'POST',
                data: { id: id, status: status },
                success: function (result) {
                    if (result.success) {
                        if (status) {
                            button.removeClass('btn-success').addClass('btn-danger').text('Đã giao');
                        } else {
                            button.removeClass('btn-danger').addClass('btn-success').text('Chưa giao');
                        }
                    } else {
                        alert(result.message);
                    }
                },
                error: function () {
                    alert('An error occurred while updating the order status.');
                }
            });
        });
    });

$(document).ready(function () {
  $(".btn-view-details").on("click", function () {
    var button = $(this);
    var orderId = button.data("id");
    var username = button.closest("tr").find("#username").text();
    var phone = button.closest("tr").find("#Sdt").text();
    var Diachi = button.closest("tr").find("#adress").text();
    $.ajax({
      url: '@Url.Action("GetOrderDetails", "Order_details")',
      type: 'POST',
      data: { orderId: orderId },
      success: function (result) {
        if (result.success) {
          var orderDetails = result.orderDetails;
          var orderDetailsContainer = $("#orderDetailsContainer");
          orderDetailsContainer.empty();
          orderDetailsContainer.append("<p> Tên NGười mua: " + username + "</p>");
          orderDetailsContainer.append("<p> Số Điện Thoại: " + phone + "</p>");
          orderDetailsContainer.append("<p> Địa Chỉ: " + Diachi + "</p>");

          if (orderDetails.length > 0) {
            var totalCost = 0;
            var orderList = $("<ul>").appendTo(orderDetailsContainer); // Create <ul> element

            orderList.append(" ========== Sản Phẩm Mua =============== "); // Add heading

            orderDetails.forEach(function (orderDetail) {
              var listItem = "<li>" +
                "Tên: " + orderDetail.productName + "<br/>" +
                "Giá: " + orderDetail.Gia + "<br/>" +
                  "Số lượng: " + orderDetail.soluong + "<br/>" +
                  " Tổng Tiền của Sản Phẩm: " + orderDetail.total +

                "</li>";
              orderList.append(listItem); // Append the list item to the <ul>

                totalCost = orderDetail.quantity;
            });

            orderDetailsContainer.append("<p> => Total Cost: " + totalCost + "</p>");
          } else {
            orderDetailsContainer.html("No order details found.");
          }

          $("#detailsModalLabel").html("Chi Tiết Hóa Đơn");
        } else {
          alert(result.message);
        }
      },
      error: function () {
        alert('An error occurred while fetching order details.');
      }
    });

  });
    $("#btnsubmit").on("click", function () {
        var modalContent = $("#detailsModal .modal-content").html();
        console.log(modalContent); // Log to the console for inspection
        $("input[name='Gridhtml']").val(modalContent);
        $("#Export_form").submit();
    });


});



</script>

<style>
    .border {
        border: 1px solid black;
        padding: 5px;
        text-align: center;
        vertical-align: middle;
    }
</style>

Food_Web/Areas/Store/Views/Order_details/Orderday.cshtml
@model PagedList.IPagedList<Food_Web.Models.Order_detail>
@using PagedList;
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Food_Web.Models
@{
    ViewBag.Title = "Order Day";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var listUser = userManager.Users.ToList();
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Trang Chủ", "Index", "Homes") / @Html.ActionLink("Voucher Giảm giá", "Index", "Discounts")</h6>
    </div>
    <div>
        @using (Html.BeginForm("Orderday", "Order_details", FormMethod.Get))
        {
            <div class="form-group">
                @Html.TextBox("od_day", null, new { @class = "form-control datepicker", @placeholder = "Select date", id = "Box" })
            </div>
            <button type="submit" id="Loc" class="btn btn-primary">Filter</button>
        }
        @Html.ActionLink("Export to Excel", "Exportod_day", new { @class = "btn btn-primary" })
    </div>

    <table class="table">
        <tr>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        STT
                    </span>
                </div>
            </td>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Tên
                    </span>
                </div>
            </td>

            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Ngày Đặt
                    </span>
                </div>
            </td>

            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Hành Động
                    </span>
                </div>
            </td>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Od_id)
                </td>
                <td class="border">
                    @foreach (var u in listUser)
                    {
                        if (u.Id == item.Order.Od_name)
                        {
                            <span id="username">@u.Fullname</span>
                            <span id="Sdt" style="display: none;">@u.PhoneNumber</span>
                            <span id="adress" style="display: none;">@u.Adress</span>
                            break;
                        }
                        else { continue; }
                    }
                </td>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Order.Od_date)
                </td>

                <td class="border">
                    <button class="btn btn-primary btn-sm btn-view-details" data-id="@item.Od_id" data-bs-toggle="modal" data-bs-target="#detailsModal">
                        <i class="fas fa-eye"></i>
                    </button>
                </td>

            </tr>
        }


    </table>
</div>
<div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="exportword">
            <div class="modal-header">
                <h5 class="modal-title" id="detailsModalLabel">Chi Tiết Hóa Đơn</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="orderDetailsContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <div>
                    @using (Html.BeginForm("ExportToWord", "Order_details", new { area = "Store" }, FormMethod.Post, new { @id = "Export_form" }))
                    {
                        <input type="hidden" name="Gridhtml" />
                        <input type="submit" id="btnsubmit" value="Export" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-3">
    <nav aria-label="Page navigation">
        <ul class="pagination">

            @if (Model.PageCount > 1)
            {
                <li class="page-item @(Model.IsFirstPage ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action("Orderday", new { page = 1, od_day = ViewBag.selcetodday })">Đầu</a>
                </li>

                <li class="page-item @(Model.IsFirstPage ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action("Orderday", new { page = Model.PageNumber - 1, od_day = ViewBag.selcetodday })">Trước</a>
                </li>

                {
                    for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                            <a class="page-link" href="@Url.Action("Orderday", new { page = i, od_day = ViewBag.selcetodday })">@i</a>
                        </li>
                    }
                }

                <li class="page-item @(Model.IsLastPage ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action("Orderday", new { page = Model.PageNumber + 1, od_day = ViewBag.selcetodday })">Sau</a>
                </li>

                <li class="page-item @(Model.IsLastPage ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action("Orderday", new { page = Model.PageCount, od_day = ViewBag.selcetodday })">Cuối</a>
                </li>
            }

        </ul>
    </nav>
</div>



@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/flatpickr.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/flatpickr.min.css">

    <script>
        flatpickr(".datepicker", {
            dateFormat: "Y-m-d",
            allowInput: true
        });

        $(document).ready(function () {
  $(".btn-view-details").on("click", function () {
    var button = $(this);
    var orderId = button.data("id");
    var username = button.closest("tr").find("#username").text();
    var phone = button.closest("tr").find("#Sdt").text();
    var Diachi = button.closest("tr").find("#adress").text();
    $.ajax({
      url: '@Url.Action("GetOrderDetails", "Order_details")',
      type: 'POST',
      data: { orderId: orderId },
      success: function (result) {
        if (result.success) {
          var orderDetails = result.orderDetails;
          var orderDetailsContainer = $("#orderDetailsContainer");
          orderDetailsContainer.empty();
          orderDetailsContainer.append("<p> Tên NGười mua: " + username + "</p>");
          orderDetailsContainer.append("<p> Số Điện Thoại: " + phone + "</p>");
          orderDetailsContainer.append("<p> Địa Chỉ: " + Diachi + "</p>");

          if (orderDetails.length > 0) {
            var totalCost = 0;
            var orderList = $("<ul>").appendTo(orderDetailsContainer); // Create <ul> element

            orderList.append(" ========== Sản Phẩm Mua =============== "); // Add heading

            orderDetails.forEach(function (orderDetail) {
              var listItem = "<li>" +
                "Tên: " + orderDetail.productName + "<br/>" +
                "Giá: " + orderDetail.Gia + "<br/>" +
                  "Số lượng: " + orderDetail.soluong + "<br/>" +
                  " Tổng Tiền của Sản Phẩm: " + orderDetail.total +

                "</li>";
              orderList.append(listItem); // Append the list item to the <ul>

                totalCost = orderDetail.quantity;
            });

            orderDetailsContainer.append("<p> => Total Cost: " + totalCost + "</p>");
          } else {
            orderDetailsContainer.html("No order details found.");
          }

          $("#detailsModalLabel").html("Chi Tiết Hóa Đơn");
        } else {
          alert(result.message);
        }
      },
      error: function () {
        alert('An error occurred while fetching order details.');
      }
    });
      $("#btnsubmit").on("click", function () {
          var gridHtml = $("#exportword").html();

          // Set the content of the hidden input field
          $("input[name='Gridhtml']").val(gridHtml);

          // Submit the form to the server
          $("#Export_form").submit();
      });
  });
});

    </script>

}
<style>
    .border {
        border: 1px solid black;
        padding: 5px;
        text-align: center;
        vertical-align: middle;
    }

    input.form-control.datepicker.flatpickr-input.flatpickr-mobile {
    }

    .form-group {
        width: 143px;
        padding-left: 13px;
        margin-left: 20px;
    }

    #Loc {
        padding-left: 13px;
        margin-left: 168px;
        margin-top: -94px;
    }
</style>

Food_Web/Areas/Store/Views/Order_details/TopAccounts.cshtml
@model IEnumerable<Food_Web.Models.Order_detail>

@{
    ViewBag.Title = "Top Accounts";
    Layout = "~/Views/Shared/_LayoutStore.cshtml";
}

<h2>Top Accounts</h2>

<table class="table">
    <tr>
        <th>Order Name</th>
        <th>Total Quantity</th>
    </tr>

    @foreach (var account in Model)
    {
        <tr>
            <td>@account.Order.Od_name</td>
            <td>@ViewBag.TotalQuantity</td>
        </tr>
    }
</table>