Food_Web/Models/Category.cs
namespace Food_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Category")]
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            Products = new HashSet<Product>();
        }

        public int Categoryid { get; set; }

        [StringLength(100)]
        public string Categoryname { get; set; }

        public string image { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

Food_Web/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using Microsoft.AspNet.Identity;

namespace Food_Web.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();

        // GET: Admin/Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Admin/Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Admin/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        public ActionResult Create(Category newcategory, HttpPostedFileBase Content)
        {

            var context = new FoodcontextDB();

            if (ModelState.IsValid)
            {

                newcategory = context.Categories.Add(newcategory);

                if (Content != null && Content.ContentLength > 0)
                {
                    var typeFile = Path.GetExtension(Content.FileName);
                    newcategory.image = newcategory.Categoryid + typeFile;
                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), newcategory.image);
                    Content.SaveAs(filePath);

                }

                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", newcategory);
        }

        // GET: Admin/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Categoryid, Categoryname")] Category newcategory, HttpPostedFileBase Content)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var find = await db.Categories.FindAsync(newcategory.Categoryid);
                    if (find == null)
                    {
                        return HttpNotFound();
                    }

                    if (Content != null && Content.ContentLength > 0)
                    {
                        string fileName = "";
                        int index = Content.FileName.IndexOf('.');
                        fileName = "ImageProduct" + newcategory.Categoryid.ToString() + "." + Content.FileName.Substring(index + 1);
                        string path = Path.Combine(Server.MapPath("~/Content/products"), fileName);
                        Content.SaveAs(path);
                        newcategory.image = fileName;
                    }
                    else
                    {
                        newcategory.image = find.image;
                    }

                    db.Entry(find).CurrentValues.SetValues(newcategory);
                    await db.SaveChangesAsync();

                    ViewBag.Categoryid = new SelectList(db.Categories, "Categoryid", "Categoryname", newcategory.Categoryid);
                    return RedirectToAction("Index");
                }
                catch
                {
                    // Handle any exceptions that occur during the saving process
                   
                    return View(newcategory);
                }
            }
            else
            {
                
                return View(newcategory);
            }
        }


        // GET: Admin/Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Food_Web/Areas/Store/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using System.IO;
using PagedList;

namespace Food_Web.Areas.Store.Controllers
{
    public class CategoriesController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();

        // GET: Store/Categories
        public ActionResult Index(int? page, string searchString)
        {
            var categories = db.Categories.AsQueryable();

            // Thực hiện tìm kiếm nếu có chuỗi tìm kiếm
            if (!string.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(c => c.Categoryname.Contains(searchString));
            }

            const int pageSize = 5;
            var pageNumber = page ?? 1;

            // Thêm OrderBy vào đây để sắp xếp dữ liệu
            categories = categories.OrderBy(c => c.Categoryname);

            var pagedCategories = categories.ToPagedList(pageNumber, pageSize);

            ViewBag.SearchString = searchString; // Truyền searchString để giữ giá trị nhập vào ô tìm kiếm
            return View(pagedCategories);
        }

        // GET: Store/Categories/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Store/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(Category category, HttpPostedFileBase Content)
        {

            var context = new FoodcontextDB();

            if (ModelState.IsValid)
            {

                category = context.Categories.Add(category);

                if (Content != null && Content.ContentLength > 0)
                {
                    var typeFile = Path.GetExtension(Content.FileName);
                    category.image = category.Categoryid + typeFile;
                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), category.image);
                    Content.SaveAs(filePath);

                }

                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", category);
        }
        // GET: Store/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Store/Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Categoryid,Categoryname,image")] Category category, HttpPostedFileBase Content)
        {
            if (ModelState.IsValid)
            {
                if (Content != null && Content.ContentLength > 0)
                {
                    var typeFile = Path.GetExtension(Content.FileName);
                    category.image = category.Categoryid + typeFile;
                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), category.image);
                    Content.SaveAs(filePath);
                }

                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }


    }
}

Food_Web/Areas/Admin/Views/Categories/Create.cshtml
@model Food_Web.Models.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Categoryname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categoryname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoryname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Food_Web/Areas/Admin/Views/Categories/Delete.cshtml
@model Food_Web.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Food_Web/Areas/Admin/Views/Categories/Details.cshtml
@model Food_Web.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3" style="display:flex; align-items:center; justify-content:space-between">
        <h6 class="m-0 font-weight-bold text-primary" style="user-select:none"><a href="~/Admin/Categories/Index">← Quay lại</a></h6>
        <button type="submit" class="btn btn-primary" href="~/Admin/Productss/Edit">Sửa</button>

    </div>
    <div class="card-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!-- Search -->
        <div class="row">
            <div class="col-md-4 box-upload">
                <label>
                    <img src="~/Content/products/@Model.image" style="height: 320px; padding: 5px 0; border-radius: 15px;" id="preview" />

                </label>
            </div>

            <div class="col-md-8">
                <div class="form-group" style="display: flex; justify-content:center">
                    <div class="col-sm-4">
                        <label>Tên Sản Phẩm: </label>
                        @Html.TextBoxFor(m => m.Categoryname, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                        @Html.ValidationMessageFor(m => m.Categoryname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })

                    </div>

                </div>
            </div>
        </div>
        </div>
</div>
    
            <script type="text/javascript">
                function showImage(upload, preview) {
                    if (upload.files && upload.files[0]) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            $(preview).attr('src', e.target.result);
                        }
                        reader.readAsDataURL(upload.files[0]);
                    }
                }
            </script>
 
        <style>
            img#preview {
                margin: 0px 24px 17px 174px
            }

            label.btnChoose {
                margin: -60px 255px;
            }

            .btnChoose input {
                display: none;
            }
        </style>

Food_Web/Areas/Admin/Views/Categories/Edit.cshtml
@model Food_Web.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="card shadow mb-4">
        <div class="card-header py-3" style="display:flex; align-items:center; justify-content:space-between">
            <h6 class="m-0 font-weight-bold text-primary" style="user-select:none"><a href="~/Admin/Categories/Index">← Quay lại</a></h6>
            <button type="submit" class="btn btn-primary" href="~/Admin/Categories/Edit">Sửa</button>

        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <!-- Search -->
            <div class="row">
                <div class="col-md-4 box-upload">
                    <label>
                        <img src="~/Content/products/@Model.image" style="height: 320px; padding: 5px 0; border-radius: 15px;" id="preview" />
                        <div class="col-md-10" style=" display: none;">
                            <input type="file" name="Content" required calss="form-control" id="images" accept=".png, .jpg, .jpeg" required onchange="showImage(this, document.getElementById('preview'))" />
                        </div>
                    </label>
                </div>

                <div class="col-md-8">
                    <div class="form-group" style="display: flex; justify-content:center">
                        <div class="col-sm-4">
                            <label>Tên Sản Phẩm: </label>
                            @Html.TextBoxFor(m => m.Categoryname, new { @class = "form-control form-control-sm", style = "width: 250px; padding: 7px 5px;" })
                            @Html.ValidationMessageFor(m => m.Categoryname, "", new { @class = "text-danger", style = "display: block; margin: 5px auto;" })

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    function showImage(upload, preview) {
        if (upload.files && upload.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(preview).attr('src', e.target.result);
            }
            reader.readAsDataURL(upload.files[0]);
        }
    }
</script>
}
<style>
    img#preview {
        margin: 0px 24px 17px 174px
    }

    label.btnChoose {
        margin: -60px 255px;
    }

    .btnChoose input {
        display: none;
    }
</style>

Food_Web/Areas/Admin/Views/Categories/Index.cshtml
@model IEnumerable<Food_Web.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Trang Chủ", "Index", "Homes") / @Html.ActionLink("Sản Phẩm", "Index", "Productss")</h6>
    </div>
    <div class="card-body">
        <table class="table">
            <tr>
                <td class="border">
                    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                            Tên
                        </span>
                    </div>
                </td>

                <td class="border">
                    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                            Ảnh
                        </span>
                    </div>
                </td>
                <td class="border">
                    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                            Hành Động
                        </span>
                    </div>
                </td>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="border">
                        @Html.DisplayFor(modelItem => item.Categoryname)
                    </td>
                    <td class="border">
                        <img src="~/Content/products/@item.image" style="width:80px" />
                    </td>

                    <td class="border">
                        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet" />
                        <a href="@Url.Action("Edit", new { id = item.Categoryid })" class="btn btn-primary btn-sm" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a href="@Url.Action("Details", new { id = item.Categoryid })" class="btn btn-info btn-sm" title="Details">
                            <i class="fas fa-info-circle"></i>
                        </a>

                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>

    function updateProductStatus(productId, status) {
  $.ajax({
    url: '@Url.Action("UpdateStatus", "Productss")',
    type: 'POST',
    data: { id: productId, status: status },
    success: function(result) {
      if (result.success) {
        // Update the button text and color
        var button = $('button[data-id="' + productId + '"]');
        if (status) {
          button.removeClass('btn-danger').addClass('btn-success').text('Còn');
        } else {
          button.removeClass('btn-success').addClass('btn-danger').text('Hết');
        }
      } else {
        alert('Có lỗi xảy ra khi cập nhật trạng thái sản phẩm.');
      }
    },
    error: function() {
      alert('Có lỗi xảy ra khi gửi yêu cầu cập nhật trạng thái sản phẩm.');
    }
  });
}


    var getID = null
    var getParent = null
    $(document).on('click', '.btnRemove', function () {
        getID = $(this).data('id')
        getParent = $(this).closest('tr')
    })
    $(document).on('click', '#confirmRemove', function () {
        $.ajax({
            type: 'POST',
            url: '/Store/Productss/RemoveProduct',
            data: { id: getID },
            success: function (result) {
                if (result.success) {
                    console.log('success')
                    getParent.remove()
                }
            }
        })
    })
</script>

<style>
    .border {
        border: 1px solid black;
        padding: 5px;
        text-align: center;
        vertical-align: middle;
    }
</style>