Food_Web/Areas/Admin/Controllers/Order_detailssController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;

namespace Food_Web.Areas.Admin.Controllers
{
    public class Order_detailssController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();

        // GET: Admin/Order_detail
        public async Task<ActionResult> Index()
        {
            var order_detail = db.Order_detail.Include(o => o.Order).Include(o => o.Product);
            return View(await order_detail.ToListAsync());
        }

        // GET: Admin/Order_detail/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order_detail order_detail = await db.Order_detail.FindAsync(id);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            return View(order_detail);
        }

        // GET: Admin/Order_detail/Create
        public ActionResult Create()
        {
            ViewBag.Od_id = new SelectList(db.Orders, "Od_id", "Od_name");
            ViewBag.Productid = new SelectList(db.Products, "Productid", "Productname");
            return View();
        }

        // POST: Admin/Order_detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Od_id,Productid,price,num,tt_money,Storeid")] Order_detail order_detail)
        {
            if (ModelState.IsValid)
            {
                db.Order_detail.Add(order_detail);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Od_id = new SelectList(db.Orders, "Od_id", "Od_name", order_detail.Od_id);
            ViewBag.Productid = new SelectList(db.Products, "Productid", "Productname", order_detail.Productid);
            return View(order_detail);
        }

        // GET: Admin/Order_detail/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order_detail order_detail = await db.Order_detail.FindAsync(id);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            ViewBag.Od_id = new SelectList(db.Orders, "Od_id", "Od_name", order_detail.Od_id);
            ViewBag.Productid = new SelectList(db.Products, "Productid", "Productname", order_detail.Productid);
            return View(order_detail);
        }

        // POST: Admin/Order_detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Od_id,Productid,price,num,tt_money,Storeid")] Order_detail order_detail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order_detail).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Od_id = new SelectList(db.Orders, "Od_id", "Od_name", order_detail.Od_id);
            ViewBag.Productid = new SelectList(db.Products, "Productid", "Productname", order_detail.Productid);
            return View(order_detail);
        }

        // GET: Admin/Order_detail/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order_detail order_detail = await db.Order_detail.FindAsync(id);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            return View(order_detail);
        }

        // POST: Admin/Order_detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Order_detail order_detail = await db.Order_detail.FindAsync(id);
            db.Order_detail.Remove(order_detail);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult GetOrderDetailss(int orderId)
        {
            try
            {
                var orderDetails = db.Order_detail
                    .Where(od => od.Od_id == orderId)
                    .ToList();

                // Prepare the data to be sent back to the client
                var result = new
                {
                    success = true,
                    orderDetails = orderDetails.Select(od => new
                    {
                        productName = od.Product.Productname,
                        Gia = od.Product.price,
                        soluong = od.num,
                        quantity = od.tt_money,
                        Status = od.Order.Od_status,
                        img = od.Product.image
                    })
                };

                return Json(result);
            }
            catch (Exception ex)
            {
                // Handle any errors and return an error response to the client
                var result = new
                {
                    success = false,
                    message = "An error occurred while retrieving order details."
                };

                // You may also log the error for further investigation
                // Log.Error(ex, "An error occurred while retrieving order details.");

                return Json(result);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Food_Web/Areas/Admin/Views/Order_detailss/Create.cshtml
@model Food_Web.Models.Order_detail

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order_detail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Od_id, "Od_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Od_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Od_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Productid, "Productid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Productid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Productid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tt_money, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tt_money, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tt_money, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Storeid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Storeid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Storeid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Food_Web/Areas/Admin/Views/Order_detailss/Delete.cshtml
@model Food_Web.Models.Order_detail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order_detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.Od_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Od_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Productname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tt_money)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tt_money)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Storeid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Storeid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Food_Web/Areas/Admin/Views/Order_detailss/Details.cshtml
@model Food_Web.Models.Order_detail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Order_detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.Od_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Od_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Productname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tt_money)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tt_money)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Storeid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Storeid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Food_Web/Areas/Admin/Views/Order_detailss/Edit.cshtml
@model Food_Web.Models.Order_detail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order_detail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Od_id)

        @Html.HiddenFor(model => model.Productid)

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tt_money, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tt_money, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tt_money, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Storeid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Storeid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Storeid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Food_Web/Areas/Admin/Views/Order_detailss/Index.cshtml
@model IEnumerable<Food_Web.Models.Order_detail>
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Food_Web.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    //IdentityDbContext context = new IdentityDbContext();
    //var listUser = context.Users.ToList();
    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var listUser = userManager.Users.ToList();
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Trang Chủ", "Index", "Homes") / @Html.ActionLink("Voucher Giảm giá", "Index", "Discounts")</h6>
    </div>
    <table class="table">
        <tr>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        STT
                    </span>
                </div>
            </td>
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Tên
                    </span>
                </div>
            </td>

            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Ngày Đặt
                    </span>
                </div>
            </td>
            @*<td class="border">
                    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                            Tổng Giá
                        </span>
                    </div>
                </td>*@
            @*<td class="border">
                    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                            Trạng Thái
                        </span>
                    </div>
                </td>*@
            <td class="border">
                <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <span style="font-weight: bold; text-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5);">
                        Hành Động
                    </span>
                </div>
            </td>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Od_id)
                </td>
                <td class="border">
                    @foreach (var u in listUser)
                    {
                        if (u.Id == item.Order.Od_name)
                        {
                            <span id="username">@u.Fullname</span>
                            <span id="Sdt" style="display: none;">@u.PhoneNumber</span>
                            <span id="adress" style="display: none;">@u.Adress</span>
                            break;
                        }
                        else { continue; }
                    }
                </td>
                <td class="border">
                    @Html.DisplayFor(modelItem => item.Order.Od_date)
                </td>

                <td class="border">
                    <button class="btn btn-primary btn-sm btn-view-details" data-id="@item.Od_id" data-bs-toggle="modal" data-bs-target="#detailsModal">
                        <i class="fas fa-eye"></i>
                    </button>
                </td>

            </tr>
        }


    </table>
</div>

</div>
<div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="detailsModalLabel">Chi Tiết Hóa Đơn</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="orderDetailsContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(".btn-approve").on("click", function () {
            var button = $(this);
            var id = button.data("id");
            var status = button.hasClass("btn-success");

            $.ajax({
                url: '@Url.Action("UpStatus", "Order_details")',
                type: 'POST',
                data: { id: id, status: status },
                success: function (result) {
                    if (result.success) {
                        if (status) {
                            button.removeClass('btn-success').addClass('btn-danger').text('Đã giao');
                        } else {
                            button.removeClass('btn-danger').addClass('btn-success').text('Chưa giao');
                        }
                    } else {
                        alert(result.message);
                    }
                },
                error: function () {
                    alert('An error occurred while updating the order status.');
                }
            });
        });
    });

$(document).ready(function () {
  $(".btn-view-details").on("click", function () {
    var button = $(this);
    var orderId = button.data("id");
    var username = button.closest("tr").find("#username").text();
    var phone = button.closest("tr").find("#Sdt").text();
    var Diachi = button.closest("tr").find("#adress").text();
    $.ajax({
      url: '@Url.Action("GetOrderDetails", "Order_detailss")',
      type: 'POST',
      data: { orderId: orderId },
      success: function (result) {
        if (result.success) {
          var orderDetails = result.orderDetails;
          var orderDetailsContainer = $("#orderDetailsContainer");
          orderDetailsContainer.empty();
          orderDetailsContainer.append("<p> Tên NGười mua: " + username + "</p>");
          orderDetailsContainer.append("<p> Số Điện Thoại: " + phone + "</p>");
          orderDetailsContainer.append("<p> Địa Chỉ: " + Diachi + "</p>");

          if (orderDetails.length > 0) {
            var totalCost = 0;
            var orderList = $("<ul>").appendTo(orderDetailsContainer); // Create <ul> element

            orderList.append(" ========== Sản Phẩm Mua =============== "); // Add heading

            orderDetails.forEach(function (orderDetail) {
              var listItem = "<li>" +
                "Tên: " + orderDetail.productName + "<br/>" +
                "Giá: " + orderDetail.Gia + "<br/>" +
                  "Số lượng: " + orderDetail.soluong + "<br/>" +
                  " Tổng Tiền của Sản Phẩm: " + orderDetail.quantity +
                "</li>";
              orderList.append(listItem); // Append the list item to the <ul>

              totalCost += orderDetail.quantity;
            });

            orderDetailsContainer.append("<p> => Total Cost: " + totalCost + "</p>");
          } else {
            orderDetailsContainer.html("No order details found.");
          }

          $("#detailsModalLabel").html("Chi Tiết Hóa Đơn");
        } else {
          alert(result.message);
        }
      },
      error: function () {
        alert('An error occurred while fetching order details.');
      }
    });
  });
});


</script>
<style>
    .border {
        border: 1px solid black;
        padding: 5px;
        text-align: center;
        vertical-align: middle;
    }
</style>