Food_Web/Areas/Store/Controllers/AccController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using Microsoft.AspNet.Identity;
using static Food_Web.Models.ManageController;

namespace Food_Web.Areas.Store.Controllers
{
    public class AccController : Controller
    {
        // GET: Store/Acc
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(userId);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }
        public ActionResult Logoff()
        {
            // Perform logout logic

            return RedirectToAction("Index", "Product");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var currentUser = await userManager.FindByNameAsync(User.Identity.Name);

                    if (currentUser != null)
                    {
                        currentUser.Email = user.Email;
                        currentUser.PhoneNumber = user.PhoneNumber;
                        currentUser.Fullname = user.Fullname;
                        currentUser.Adress = user.Adress;
                        currentUser.Opentime = user.Opentime;
                        currentUser.Closetime = user.Closetime;
                        // Gán các thuộc tính khác của người dùng từ form

                        var result = await userManager.UpdateAsync(currentUser);

                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            // Xử lý khi cập nhật thất bại
                            // Có thể thêm các thông báo lỗi vào ModelState
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error);
                            }
                        }
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
                catch (Exception)
                {
                    // Xử lý khi có lỗi xảy ra trong quá trình lưu dữ liệu
                    ModelState.AddModelError("", "An error occurred while saving the user.");
                }
            }

            return View("Index", user);
        }
        // Get View using this Method

    }
}

Food_Web/Areas/Store/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Web.Models;
using System.IO;
using PagedList;

namespace Food_Web.Areas.Store.Controllers
{
    public class CategoriesController : Controller
    {
        private FoodcontextDB db = new FoodcontextDB();

        // GET: Store/Categories
        public ActionResult Index(int? page, string searchString)
        {
            var categories = db.Categories.AsQueryable();

            // Thực hiện tìm kiếm nếu có chuỗi tìm kiếm
            if (!string.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(c => c.Categoryname.Contains(searchString));
            }

            const int pageSize = 5;
            var pageNumber = page ?? 1;

            // Thêm OrderBy vào đây để sắp xếp dữ liệu
            categories = categories.OrderBy(c => c.Categoryname);

            var pagedCategories = categories.ToPagedList(pageNumber, pageSize);

            ViewBag.SearchString = searchString; // Truyền searchString để giữ giá trị nhập vào ô tìm kiếm
            return View(pagedCategories);
        }

        // GET: Store/Categories/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Store/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(Category category, HttpPostedFileBase Content)
        {

            var context = new FoodcontextDB();

            if (ModelState.IsValid)
            {

                category = context.Categories.Add(category);

                if (Content != null && Content.ContentLength > 0)
                {
                    var typeFile = Path.GetExtension(Content.FileName);
                    category.image = category.Categoryid + typeFile;
                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), category.image);
                    Content.SaveAs(filePath);

                }

                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", category);
        }
        // GET: Store/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Store/Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Categoryid,Categoryname,image")] Category category, HttpPostedFileBase Content)
        {
            if (ModelState.IsValid)
            {
                if (Content != null && Content.ContentLength > 0)
                {
                    var typeFile = Path.GetExtension(Content.FileName);
                    category.image = category.Categoryid + typeFile;
                    var filePath = Path.Combine(Server.MapPath("~/Content/products"), category.image);
                    Content.SaveAs(filePath);
                }

                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }


    }
}

Food_Web/Areas/Store/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Food_Web.Areas.Store.Controllers
{
    public class TimeController : Controller
    {
        // GET: Store/Time
        public ActionResult Index()
        {
            return View();
        }
    }
}

Food_Web/Controllers/StoresController.cs
using Food_Web.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Threading.Tasks;
using System.Data.Entity;
using PagedList;
using System.IO;
using Microsoft.AspNet.SignalR;


namespace Food_Web.Models
{
    public class StoresController : Controller
    {

        //public ActionResult Index(string storeid)
        //{
        //    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        //    var userList = userManager.Users.Where(u => u.IsApproved).ToList();
        //    return View(userList);
        //}
        public ActionResult Index(string storeid)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            // Get the current time
            var currentTime = DateTime.Now.TimeOfDay;

            // Get the list of users filtered by the storeid and opening hours
            var userList = userManager.Users.Where(u => u.IsApproved).ToList();

            foreach (var user in userList)
            {
                // Compare the current time with the opening and closing hours
                if (currentTime < user.Opentime || currentTime > user.Closetime)
                {
                    user.status = "Closed";
                    ViewBag.Status = user.status;
                }
                else
                {
                    user.status = "Open";
                    ViewBag.Status = user.status;
                }
            }

            // Store the open or closed status in the ViewBag
            

            return View(userList);
        }
        private FoodcontextDB db = new FoodcontextDB();
        public ActionResult Details(string id)
        {
             
                 int productId;
            if (!int.TryParse(id, out productId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(productId);
            if (product == null)
            {
                return HttpNotFound();
            }

            // Continue with your code logic to display the product details

            return View(product);
        }


        public static string getIdStore = "";
       
        public ActionResult StoreProducts(string id)
            {
            Session["CurrentStoreId"] = id;
            
            getIdStore = id;
                if (string.IsNullOrEmpty(id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                using (var db = new ApplicationDbContext())
                {
                    var products = db.Products.Where(p => p.Userid == id).ToList();
                    ViewBag.userId = id;
                    var user = db.Users.FirstOrDefault(u => u.Id == id);
                    if (user != null)
                    {
                        ViewBag.userName = user.UserName;
                    }

                return View(products);
                }
            }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "content, created_at, Rating, storeId")] Comment comment, string storeId, HttpPostedFileBase image)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                using (var db = new FoodcontextDB())
                {
                    // Retrieve the maximum comment_id from the database
                    int maxCommentId = db.Comments.Max(c => c.comment_id);

                    // Increment the comment_id by 1 to generate a new unique ID
                    comment.comment_id = maxCommentId + 1;

                    // Set the user_id and Store_id
                    comment.user_id = User.Identity.GetUserId();
                    comment.Store_id = storeId;
                    comment.created = DateTime.Now;

                    // Handle the uploaded image
                    if (image != null && image.ContentLength > 0)
                    {
                        // Save the image and get the image path
                        string imagePath = SaveImage(image);

                        // Set the image path in the comment
                        comment.img = imagePath;
                    }

                    db.Comments.Add(comment);
                    await db.SaveChangesAsync();
                }

                return RedirectToAction("StoreProducts", new { id = storeId });
            }

            return View("StoreProducts");
        }

        // Helper method to save the image and return the image path
        private string SaveImage(HttpPostedFileBase image)
        {
            // Ensure the ~/Content/products directory exists, create it if necessary
            string uploadDir = Server.MapPath("~/Content/products");
            if (!Directory.Exists(uploadDir))
            {
                Directory.CreateDirectory(uploadDir);
            }

            // Get a unique filename for the image
            string fileName = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);

            // Specify the path where you want to save the image
            string imagePath = Path.Combine(uploadDir, fileName);

            // Save the image to the specified path
            image.SaveAs(imagePath);

            // Return the relative image path
            return "/Content/products/" + fileName;
        }



        public ActionResult ShowComment(string storeId)
        {
            storeId = getIdStore;
            using (var db = new FoodcontextDB())
            {
                var comments = db.Comments.Where(c => c.Store_id == storeId).ToList();
                return View(comments);
            }
        }


        public ActionResult HotProducts(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new ApplicationDbContext())
            {
                var products = db.Products.Where(p => p.Userid == id && p.is_hot == true).ToList();
                return View(products);
            }
        }

        public async Task<ActionResult> Sale1(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new ApplicationDbContext())
            {
                var products = db.Products.Where(p => p.Userid == id && p.DiscountPercent != null).ToList();
                return View(products);
            }
        }



        public async Task<ActionResult> Indexchat()
        {

            var userId = User.Identity.GetUserId();

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var userMessages = await db.Messages
                .Where(m => m.Userid == userId)
                .ToListAsync();

            return View(userMessages);
        }
        
        public async Task<ActionResult> GetMessages(string storeid)
        {
            Session["CurrentStoreId"] = storeid;
            string userid = User.Identity.GetUserId();
            try
            {
                var userMessages = await db.Messages
                    .Where(m => m.Storeid == storeid && m.Userid == userid)
                    .OrderBy(m => m.Time)
                    .ToListAsync();

                return Json(new { success = true, listMessage = userMessages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError, "Error retrieving messages: " + ex.Message);
            }
        }

        public JsonResult postMessage(string message, HttpPostedFileBase image)
        {
            string Userid = User.Identity.GetUserId();
            string storeid = Session["CurrentStoreId"] as string;
            TimeSpan timeDuration = DateTime.Now.TimeOfDay;

            if (storeid != null)
            {



                // Create a new message with message text, user, store, time, and image path
                int max = db.Messages.Max(c => c.Id);
                Message mess = new Message
                {
                    Id = max + 1,
                    Content = message,
                    Userid = User.Identity.GetUserId(),
                    Storeid = storeid,
                    Time = timeDuration,

                };

                db.Messages.Add(mess);
                db.SaveChanges();

                // Tạo kết nối tới SignalR Hub
                var hubContext = GlobalHost.ConnectionManager.GetHubContext<ChatHub>();
                hubContext.Clients.User(Userid).SendPrivateMessage(storeid, message);
                hubContext.Clients.All.addNewMessageToPage(storeid, message);

                return Json(new { success = true });
            }

            return Json(new { success = false, storeid = storeid });
        }
        
    }
}

Food_Web/Views/Stores/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

Food_Web/Views/Stores/HotProducts.cshtml
@{
    ViewBag.Title = "HotProducts";
    Layout = null;
}

<!-- Page Introduction Wrapper /- -->
<!-- Custom-Deal-Page -->
<div class="page-deal u-s-p-t-80">
    <div class="container">

        <!-- //end Toolbar Sorter 1  -->
        <!-- Toolbar Sorter 2  -->
        <!-- Page-Bar /- -->
        <!-- Row-of-Product-Container -->
        <div class="row product-container grid-style">
            @foreach (var item in Model)
            {
                <div class="product-item col-lg-3 col-md-6 col-sm-6">
                    <div class="item">
                        <div class="image-container">
                            <a class="item-img-wrapper-link" href="@Url.Action("Detail", "Home", new { id = item.Productid })">
                                <img class="img-fluid" src="~/Content/products/@item.image" alt="Product">
                            </a>
                            <div class="item-action-behaviors">
                                <a class="item-quick-look" data-toggle="modal" href="#quick-view">Quick Look</a>
                                <a class="item-mail" href="javascript:void(0)">Mail</a>
                                <a class="item-addwishlist" href="javascript:void(0)" data-id="@item.Productid">Add to Wishlist</a>
                                <a class="item-addCart" href="javascript:void(0)" data-id="@item.Productid">Add to Cart</a>
                            </div>
                        </div>
                        <div class="item-content">
                            <div class="what-product-is">
                                <ul class="bread-crumb">
                                    <li class="has-separator">
                                        <a href="shop-v1-root-category.html">home</a>
                                    </li>
                                    <li class="has-separator">
                                        <a href="shop-v2-sub-category.html">Ten shop</a>
                                    </li>
                                    <li>
                                        <a href="shop-v3-sub-sub-category.html">the loai</a>
                                    </li>
                                </ul>
                                <h6 class="item-title">
                                    <a href="single-product.html">@item.Productname</a>
                                </h6>
                                <div class="item-stars">
                                    <div class='star' title="0 out of 5 - based on 0 Reviews">
                                        <span style='width:0'></span>
                                    </div>
                                    <span>(0)</span>
                                </div>
                                <div class="section-2-short-description u-s-p-y-14">
                                    <h6 class="information-heading u-s-m-b-8">Description:</h6>
                                    <p>
                                        @item.discription
                                    </p>
                                </div>
                            </div>
                            <div class="price-template">

                                <div class="item-new-price">
                                    @item.DiscountedPrice
                                </div>

                                <div class="item-new-price">
                                    @item.price
                                </div>
                                <div class="tag new">
                                    <span>Hot</span>
                                </div>


                            </div>
                        </div>

                    </div>
                </div>
            }

        </div>
    </div>
</div>

Food_Web/Views/Stores/Index.cshtml
@model IEnumerable<Food_Web.Models.ApplicationUser>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Page Introduction Wrapper /- -->
<!-- Custom-Deal-Page -->
<div class="page-deal u-s-p-t-80">
    <div class="container">
        @*<div class="deal-page-wrapper">
                <h1 class="deal-heading">New Arrivals</h1>
                <h6 class="deal-has-total-items">27 Items</h6>
            </div>*@
        <!-- Page-Bar -->
        <div class="page-bar clearfix">
            <div class="shop-settings">
                <a id="list-anchor">
                    <i class="fas fa-th-list"></i>
                </a>
                <a id="grid-anchor" class="active">
                    <i class="fas fa-th"></i>
                </a>
            </div>
            <!-- Toolbar Sorter 1  -->
            <div class="toolbar-sorter">
                <div class="select-box-wrapper">
                    <label class="sr-only" for="sort-by">Sort By</label>
                    <select class="select-box" id="sort-by">
                        <option selected="selected" value="">Sort By: Best Selling</option>
                        <option value="">Sort By: Latest</option>
                        <option value="">Sort By: Lowest Price</option>
                        <option value="">Sort By: Highest Price</option>
                        <option value="">Sort By: Best Rating</option>
                    </select>
                </div>
            </div>
            <!-- //end Toolbar Sorter 1  -->
            <!-- Toolbar Sorter 2  -->
            <div class="toolbar-sorter-2">
                <div class="select-box-wrapper">
                    <label class="sr-only" for="show-records">Show Records Per Page</label>
                    <select class="select-box" id="show-records">
                        <option selected="selected" value="">Show: 8</option>
                        <option value="">Show: 16</option>
                        <option value="">Show: 28</option>
                    </select>
                </div>
            </div>
            <!-- //end Toolbar Sorter 2  -->
        </div>
        <!-- Page-Bar /- -->
        <!-- Row-of-Product-Container -->
        <div class="row product-container grid-style">
            @foreach (var item in Model)
            {
                if (item.status == "Open")
                {
                    <div class="product-item col-lg-3 col-md-6 col-sm-6">
                        <div class="item">
                            <div class="image-container">
                                <a href="@Url.Action("StoreProducts", "Stores", new { id = item.Id })">

                                    <img class="img-fluid product-image" src="~/Content/products/@item.image">

                                    <div src="~/Content/products/@item.image" class="team-img back-img">
                                        <div class="overlay">
                                            <p class="closed-text">Đóng cửa</p>
                                        </div>
                                    </div>
                                </a>

                            </div>
                            <div class="item-content">
                                <div class="what-product-is">

                                    <h6 class="item-title">
                                        <a @Url.Action("StoreProducts", "Stores", new { id = item.Id })> </a>
                                    </h6>
                                    <div class="item-stars">
                                        <div class='star' title="0 out of 5 - based on 0 Reviews">
                                            <span style='width:0'></span>
                                        </div>
                                        <span>(0)</span>
                                    </div>
                                    <div class="section-2-short-description u-s-p-y-14">
                                        <p>
                                            @Html.ActionLink(item.UserName, "StoreProducts", "Stores", new { id = item.Id }, null)
                                            <input type="hidden" name="storeId" value="@ViewBag.userId" />
                                        </p>
                                    </div>
                                </div>
                                <div class="price-template">

                                    <div class="item-new-price">
                                        <p>@item.Opentime - @item.Closetime</p>

                                    </div>
                                </div>
                                <div class="item-new-price">
                                    <p>@item.status</p>
                                </div>
                            </div>

                        </div>
                    </div>
                }
                else
                {
                    <div class="product-item col-lg-3 col-md-6 col-sm-6">
                        <div class="item">
                            <div class="image-container">
                                <a href="@Url.Action("StoreProducts", "Stores", new { id = item.Id })" class="disabled-link">

                                    <img class="img-fluid product-image" src="~/Content/products/@item.image">

                                    <div src="~/Content/products/@item.image" class="team-img back-img">
                                        <div class="overlay">
                                            <p class="closed-text">Đóng cửa</p>
                                        </div>
                                    </div>
                                </a>

                            </div>
                            <div class="item-content">
                                <div class="what-product-is">
                                    @*<h6 class="item-title">
                                            <a @Url.Action("StoreProducts", "Stores", new { id = item.Id }) class="disabled-link" a>
                                        </h6>*@
                                    <div class="item-stars">
                                        <div class='star' title="0 out of 5 - based on 0 Reviews">
                                            <span style='width:0'></span>
                                        </div>
                                        <span>(0)</span>
                                    </div>

                                    <div class="section-2-short-description u-s-p-y-14">
                                        <p>
                                            @Html.ActionLink(item.UserName, "StoreProducts", "Stores", new { id = item.Id }, new { @class = "disabled-link" })
                                            <input type="hidden" name="storeId" value="@ViewBag.userId" />
                                        </p>
                                    </div>



                                </div>
                                <div class="price-template">

                                    <div class="item-new-price">
                                        <p>@item.Opentime - @item.Closetime</p>

                                    </div>

                                </div>
                                <div class="item-new-price">
                                    <p>@item.status</p>
                                </div>
                            </div>

                        </div>
                    </div>
                }
            }
        </div>
        <!-- Row-of-Product-Container /- -->
        <!-- Shop-Pagination -->
        <div class="pagination-area">
            <div class="pagination-number">
                <ul>
                    <li style="display: none">
                        <a href="shop-v1-root-category.html" title="Previous">
                            <i class="fa fa-angle-left"></i>
                        </a>
                    </li>
                    <li class="active">
                        <a href="shop-v1-root-category.html">1</a>
                    </li>
                    <li>
                        <a href="shop-v1-root-category.html">2</a>
                    </li>
                    <li>
                        <a href="shop-v1-root-category.html">3</a>
                    </li>
                    <li>
                        <a href="shop-v1-root-category.html">...</a>
                    </li>
                    <li>
                        <a href="shop-v1-root-category.html">10</a>
                    </li>
                    <li>
                        <a href="shop-v1-root-category.html" title="Next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Shop-Pagination /- -->
    </div>
</div>
<style>
    .product-image {
        width: 253px;
        height: 253px;
        object-fit: cover;
    }

    .disabled-link {
        pointer-events: none;
        opacity: 0.5;
    }

    .team-img {
        position: relative;
    }

    .team-img {
        position: relative;
        overflow: hidden; /* Ensure the image does not exceed the container */
    }

    .overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5); /* Gray color with transparency */
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .closed-text {
        color: red;
        text-align: center;
        font-size: 50px; /* Adjust the font size as needed */
        font-weight: bold; /* Make the text bold */
    }

    .no-link-hover {
        text-decoration: none;
        color: inherit;
    }

    .disabled-link {
        pointer-events: none;
        cursor: default;
        color: inherit;
        text-decoration: none;
    }
</style>